parameter_files:
  tags:
    - mom6-ci-c5
  script:
    #- make -f tools/MRS/Makefile m6e-pipeline -j
    - module unload PrgEnv-gnu
    - module unload PrgEnv-intel
    - module unload PrgEnv-nvhpc
    - module load PrgEnv-gnu
    - module load cray-hdf5
    - module load cray-netcdf
    - module switch gcc-native/12.3
    - module load python

    - git submodule update --init --recursive

    - echo "CC = cc" >> config.mk
    - echo "MPICC = cc" >> config.mk
    - echo "FC = ftn" >> config.mk
    - echo "MPIFC = ftn" >> config.mk
    - echo "FCFLAGS = -g -O0 -fbacktrace" >> config.mk
    - echo "LAUNCHER = srun" >> config.mk
    - echo "LAUNCHER_NP_FLAG = -n" >> config.mk
    - echo "LAUNCHER_FLAGS = -mblock --exclusive" >> config.mk
    - echo "PYTHON = python3" >> config.mk

    - make -j test.ocean_only
